[Unit]
Requires=greyward-opensnitch-control-plane.service
After=greyward-opensnitch-control-plane.service

[Service]
ExecStartPre=/usr/libexec/greyward-opensnitch-daemon-configure
ExecStart=
ExecStart=/usr/bin/opensnitchd --config-file /run/greyward-opensnitch/daemon-config.json
ExecStartPost=/usr/bin/bash -c 'if [[ -e /var/log/opensnitchd.log ]]; then chown root:wheel /var/log/opensnitchd.log && chmod 0640 /var/log/opensnitchd.log; fi'
